language: generic
sudo: required
dist: xenial
before_install:
  - bash scripts/hugoinstall.sh
  - bash scripts/rcloneinstall.sh
script:
  - make prod
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    repo: gary-kim/gomod.garykim.dev
    branch: master
    condition: $TRAVIS_PULL_REQUEST == false
